### ISSUE TITLE
运行异常

### ISSUE THREAD

**Issue by zfm076** [wwj718/codelab_adapter_wechat_node#1]
奇怪，相关的库都已经安装了，也安装成功了。在vscode直接复制你的py内容运行，vscode没运行就有波浪线标红itchat没有里面的成员，F5运行如下提示：
发生异常: AttributeError
module 'itchat' has no attribute 'auto_login'

难道是需要vscode配置文件么？

**Comment by zfm076** [comment]
> 奇怪，相关的库都已经安装了，也安装成功了。在vscode直接复制你的py内容运行，vscode没运行就有波浪线标红itchat没有里面的成员，F5运行如下提示：
> 发生异常: AttributeError
> module 'itchat' has no attribute 'auto_login'
> 
> 难道是需要vscode配置文件么？

哈哈 知道原因了。是因为我命名itchat.py文件  重命名了。换个名字即可。

不过运行提示：
<error><ret>1203</ret><message>为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。看来没办法了。

**Comment by wwj718** [comment]
是的 微信逐渐封锁web登陆机制
